name: AtmoPulse
description: "AtmoPulse : Une application de météo intuitive qui fournit des prévisions précises et des informations climatiques en temps réel. Avec AtmoPulse, restez connecté aux conditions météorologiques actuelles, découvrez les tendances et préparez-vous à chaque changement de temps."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  mysql1: ^0.20.0
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.0.15
  flutter_launcher_icons: ^0.14.1
  flip_card: ^0.7.0
  provider: ^6.0.0
  flutter_dotenv: ^5.0.2
  background_fetch: 
    git:
      url: https://github.com/transistorsoft/flutter_background_fetch
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: any
  build_runner: any 

flutter:
  uses-material-design: true
  assets: 
    - assets/.env 

fonts:
  - family: Montserrat
    fonts:
      - asset: fonts/Montserrat-Regular.ttf
      - asset: fonts/Montserrat-Bold.ttf
        weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true
